import enum


class TASKS(enum.StrEnum):
    """Copied from Open WebUI's constants at OWUI 0.9.2+."""

    QUERY = "query"
    GENERATE = "generate"
    SUMMARIZE = "summarize"
    TITLE = "title"
    TAGS = "tags"
    EMOJI = "emoji"
    SEARCH_QUERY = "search_query"
    FUNCTION = "function"
    CODE = "code"
    PLAN = "plan"
    SYNTHESIZE = "synthesize"
    OUTLINE = "outline"
    REVIEW = "review"
    VERIFY = "verify"
    BIBLIOGRAPHY = "bibliography"
    RELEVANCE = "relevance"
    RANK = "rank"
    FILTER = "filter"
    EXTRACT = "extract"
    CLASSIFY = "classify"
    COMPRESS = "compress"
    COMPARE = "compare"
    ANALYZE = "analyze"
    EXPLAIN = "explain"
    DEBUG = "debug"
    OPTIMIZE = "optimize"
    REFACTOR = "refactor"
    TRANSLATE = "translate"
